Разметка главной страницы
htmlacademy-htmlcss/1575559-sedona-29 pull request #3
Opened 2020-09-24 08:53 UTC by Rimma-1901

2020-09-25 02:42 UTC, sergeiwerty requested changes
Хорошее начало!
В основном нужно исправить повторяющиеся неточности в используемых тегах. По большей части всё сразу сделано вдумчиво (Like!)

2020-09-25 02:42 UTC, sergeiwerty commented on index.html
> +    <h1>СЕДОНА - НЕБОЛЬШОЙ ГОРОДОК В АРИЗОНЕ. ЗАСЛУЖИВАЮЩАЯ БОЛЬШЕГО</h1>
Можно не писать весь текст капсом (здесь и далее во всех подобных случаях), а потом просто задать text-transform: uppercase через css. Такой подход более гибкий.

2020-09-25 02:42 UTC, sergeiwerty commented on index.html
> +      <span>-№1-</span>
А это как раз тот случай, когда span идеально подходит (32 строка).

2020-09-25 02:42 UTC, sergeiwerty commented on index.html
> +      <span>Text</span>
Здесь и везде в подобных случаях есть более семантичная замена для span

2020-09-25 02:42 UTC, sergeiwerty commented on index.html
> +  <section>
Оборачивание в section здесь кажется излишним. Элемент h1 и текст, идущий под не имеют какой-то крепкой смысловой связи, ну и в обёртке здесь нет необходимости (если бы была - то div)

2020-09-25 02:42 UTC, sergeiwerty commented on index.html
> +    <div>
figure оборачивать в div здесь, пожалуй, нет необходимости, а сам figure подошёл бы больше где-то на странице с преимущественно текстовым содержимым (в качестве указания на демонстрационный характер своего содержимого)

2020-09-25 02:42 UTC, sergeiwerty commented on index.html
> +  <section>
Дальше идут подряд крайне схожие по смыслу и внешнему виду элементы - может список?

2020-09-25 02:42 UTC, sergeiwerty commented on index.html
> +      <span>РЕКОМЕНДУЕМ ПОЖИТЬ В НСТОЯЩЕМ МОТЕЛЕ, ВСЕ КАКУ В КИНО</span>
Строки 44, 50, 56 - есть лучшая альтернатива span'у

2020-09-25 02:42 UTC, sergeiwerty commented on index.html
> +  <section>
По сути повторяется всё то же самое, что и для блока под номером 1 (настоящий городок)

2020-09-25 02:42 UTC, sergeiwerty commented on index.html
> +  <section>
Также можно присмотреться к некоторым тегам в этом section'е и заменить, исходя из критериев, описанных выше

2020-09-25 02:42 UTC, sergeiwerty commented on index.html
> +    #VISITSEDONA
Тут ещё телефона не хватает а сам хештег идеально впишется в тег p

2020-09-25 02:42 UTC, sergeiwerty commented on index.html
> +        <a href="#">Twitter</a>
Пусть у этих ссылок атрибут будет просто пустым

2020-09-25 02:42 UTC, sergeiwerty commented on index.html
> +    <img src="https://via.placeholder.com/150x100" alt="">
логотип академии должен вести на её сайт (пункт 3.8 обязательных требований)

2020-09-28 13:03 UTC, Rimma-1901 commented
Сергей, я сделала изменения. Пожалуйста, посмотрите.

2020-09-29 06:05 UTC, sergeiwerty requested changes

2020-10-02 20:34 UTC, sergeiwerty requested changes
Разметка элементов внутри фильтра - это рывок далеко за рамки данного шага. Похвально. Но с ним можно потом поработать, чтобы продвинуться быстрее к стилизации и сеткам.
Ну а так - всё хорошо.

2020-10-02 20:34 UTC, sergeiwerty commented on inner_page.html
> +      <div class="filter_infr">
На этом этапе пока фильтр не обязательно было размечать, но если он есть, то и тегом пусть будет сделан соответствующим, т.е. тем, что предназначен для отправки данных на сервер

2020-10-02 20:34 UTC, sergeiwerty commented on inner_page.html
> +        <input type="checkbox" name="swimming_pool" id="swimming_pool" checked>
Очень будет кстати сгруппировать каждую группу чекбоксов, хотя я не настаиваю на том, чтобы вы это делали сейчас. Потом можете просто вернуться и посмотреть эти комментарии.

2020-10-02 20:34 UTC, sergeiwerty commented on inner_page.html
> +        <p>Инфраструктура:</p>
Для наименования, обозначающего принадлежность к опциям (и в других подобных случаях) для интерактивных элементов существует специальный тег.

2020-10-02 20:34 UTC, sergeiwerty commented on inner_page.html
> +      <button type="submit">Отправить</button>
Точнее "Показать"

2020-10-02 20:34 UTC, sergeiwerty commented on inner_page.html
> +          <input type="submit" value="Подробнее">
Когда мы нажмём "Подробнее", то скорее всего сможем перейти на какую-то другую страницу

2020-10-02 20:34 UTC, sergeiwerty commented on inner_page.html
> +    <div class="hotels">
Отели это ведь по сути список однотипных элементов

2020-10-02 20:34 UTC, sergeiwerty commented on inner_page.html
> +          гостиница от 4000 Р.
Тип жилья и его цена - это по сути 2 отдельных элемента

2020-10-02 20:34 UTC, sergeiwerty commented on inner_page.html
> +        <div class="rating">
если есть что-то, что очень похоже на список - лучше его и использовать

2020-10-02 20:34 UTC, sergeiwerty commented on inner_page.html
> +    <p>#VISITSEDONA</p><br>
А можно просто сделать 2 отдельных p и тогда перенос будет автоматом, да p внутри p - не пройдёт валидацию

2020-10-02 20:34 UTC, sergeiwerty commented on inner_page.html
> +  </div>
Одинокий div. К сожалению ему не место в мире парных тегов

2020-10-09 14:02 UTC, sergeiwerty requested changes

2020-10-09 14:02 UTC, sergeiwerty commented on inner_page.html
> +        <li><a href="#">по цене</a></li>
Если мы щёлкнем на эти элементы с текстом (по цене, по типу, по рейтингу), то изменятся отображаемые данные на данной странице и никакого перехода не произойдёт, т.е. функционал будет реализован на JavaScript и сделать их лучше кнопками

2020-10-13 19:41 UTC, sergeiwerty requested changes
Везде нужно убрать позиционирование, а взамен использовать гораздо более гибкие механизмы флексов, гридов и другие подходы

2020-10-13 19:41 UTC, sergeiwerty commented on index.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700&amp;subset=latin,cyrillic;display=swap">
Со шрифтом ошибка какая-то - он не подключился. И шрифт не PT Sans Narrow, а просто PT Sans.
Для данного макета корректное подключение должно выглядеть так: 
href="https://fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&display=swap" rel="stylesheet"

2020-10-13 19:41 UTC, sergeiwerty commented on css/inner_page.css
> +  position: absolute;
Позиционирование только усложняет здесь работу с элементами. Без него всё можно сделать гораздо проще.

2020-10-13 19:41 UTC, sergeiwerty commented on css/inner_page.css
> +  font-family: "PT Sans";
Очень удобно задать для body основные шрифтовые свойства, повторяющиеся на всех страницах, тогда механизм наследования сделает много работы за вас

2020-10-13 19:41 UTC, sergeiwerty commented on css/inner_page.css
> +  height: 2762px;
Стоит избегать фиксированных значений для высоты страницы. Гораздо лучше использовать подход где heigth: 100%

2020-10-13 19:41 UTC, sergeiwerty commented on css/inner_page.css
> +  height: 56px;
Всё, что относится к позиционированию необходимо удалить. Контент будет располагаться с использованием гораздо более гибких способов

2020-10-13 19:41 UTC, sergeiwerty commented on css/inner_page.css
> +  position: absolute;
Позиционирование убрать

2020-10-13 19:45 UTC, sergeiwerty requested changes
.

2020-10-16 13:44 UTC, sergeiwerty requested changes
Хорошая работа продела. 👍 Осталось "дожать" футер и можно двигаться дальше!

Общее требование к проекту: по критерию Б2 Все стили проекта написаны и подключены в одном файле. Сейчас в папке css присутствует второй стилевой файл inner_page.css.

2020-10-16 13:44 UTC, sergeiwerty commented on css/style.css
> +  font-weight: 256px;
у свойства font-weigth все значения кратны 100

2020-10-16 13:44 UTC, sergeiwerty commented on css/style.css
> +  width: 1280px;
Сейчас ваш макет имеет фиксированное значение 1280px - понимаю, вы взяли это значение из макета (вся макетная ширина), но те самые +80px (серые полосы по краям контента) - это просто демонстрация, как выглядит тень за краями контентной области при ширине вьюпорта более 1200px.

Вот как сейчас это выглядит: 
![изображение](https://user-images.githubusercontent.com/30851572/96262701-d5d13480-0fca-11eb-8ad5-4146d430b96f.png)
Получается, что отобразились белые полосы по краям от фона с горами, в макете этого нет и за ним сразу начинается тень.

2020-10-16 13:44 UTC, sergeiwerty commented on css/style.css
> +  top: 0px;
left и top здесь не нужны, да и не будут работать, т.к. элемент с .page-body не имеет значений position отличных от static

2020-10-16 13:44 UTC, sergeiwerty commented on css/style.css
> +.banner-inform {
Сейчас фон с горами добавлен в вёрстку и это немного усложняет работу с ним, т.к. чтобы добавить приветственные изображения-текст, нужно будет работать с позиционированием. 
Есть более логичный и простой подход - задать фон с горами именно фоном :), т.е. добавить его в качестве background-image для header или banner-inform (на ваше усмотрение), а текст-изображение просто вложить внутрь него.

2020-10-16 13:44 UTC, sergeiwerty commented on css/style.css
> +.poyasnenie {
Транслит детектед!!!

2020-10-16 13:44 UTC, sergeiwerty commented on css/style.css
> +.zag {
Предположим я разработчик, который работает спустя время с данным css-кодом. Я встречаю подобное название класса и скорее всего захочу его убрать или изменить, т.к. догадаться о его назначении не представляется возможным, к сожалению.

2020-10-16 13:44 UTC, sergeiwerty commented on css/style.css
> +.block3 {
Я пытался найти что-то с классами .block1 и .block2, но не удалось, тогда пожалуй и .block3 надо что-то делать...

И еще: сейчас текст "Заинтересовались..." наследует шрифтовые свойства от родителя, а они его полнят :-)

2020-10-18 09:39 UTC, merged